server_address = "0.0.0.0:3000"
database_url = "postgresql://postgres:password@localhost:5432/mutation_tester"
log_level = "info"
jaeger_endpoint = "http://localhost:14268/api/traces"
prometheus_endpoint = "0.0.0.0:9090"
loki_endpoint = "http://localhost:3100"
environment = "development"
service_name = "mutation-tester-backend"
service_version = "0.1.0"